executable = PStags.bash
output = log.d/stdout.$(CLUSTER).$(PROCESS)
error = log.d/stderr.$(CLUSTER).$(PROCESS)
log = PStags.log
notification = never
universe = vanilla
should_transfer_files = yes
#x509userproxy=/tmp/x509up_u7896
#+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/rjones30/gluextest:latest"
#transfer_input_files = setup_centos7.sh,PStags_files.list,/tmp/vt_u7896,/home/jonesrt/.config/htgettoken/credkey-jlab-gluex,epoch_time_limits
transfer_input_files = setup_centos7.sh,PStags_files.list,/tmp/vt_u7896,/home/jonesrt/.config/htgettoken/credkey-jlab-gluex
WhenToTransferOutput = ON_EXIT
on_exit_hold = (ExitBySignal==False)&&(ExitCode!=0)&&(JobRunCount > 3)
on_exit_remove = (ExitBySignal==False)&&(ExitCode==0)
RequestMemory = 4200
RequestCPUs = 4
+JobType = "Urgent"
arguments = $(PROCESS)
queue 7
