executable = TAGMtrees.bash
output = log.d/stdout.$(CLUSTER).$(PROCESS)
error = log.d/stderr.$(CLUSTER).$(PROCESS)
log = TAGMtrees.log
notification = never
universe = vanilla
arguments = $(PROCESS)
should_transfer_files = yes
#x509userproxy=/tmp/x509up_u7896
transfer_input_files = setup_alma9.sh,TAGMtrees_runs.list,/tmp/vt_u7896
WhenToTransferOutput = ON_EXIT
on_exit_hold = (ExitBySignal==False)&&(ExitCode!=0)
on_exit_remove = (ExitBySignal==False)&&(ExitCode==0)
RequestCPUs = 4
Requirements = (TARGET.OpSysName=="AlmaLinux")
+JobType = "Urgent"
queue 80
